### ISSUE TITLE
nevra, wtf?

### ISSUE THREAD

**Issue by durandom** [goern/nevra-resolver#1]
* nevra is RPM naming convention: name-version-release.architecture, where version may
 * contain epoch at the beginning separated by colon

see some code examples [here](https://www.spinics.net/lists/rpm-ecosystem/msg00472.html)

**Comment by goern** [comment]
Correct, and if you have a look at the source, this repository is just about providing a containerized web service that returns some JSON based on the input package name... it's a nano service!
